-- ─────────────────────────────────────────────────────────────────────────────
-- KOHĪ Marketplace — products table
-- Run this in the Supabase SQL Editor (SQL → New query → paste → Run)
-- ─────────────────────────────────────────────────────────────────────────────


-- 1. Create table ─────────────────────────────────────────────────────────────

create table public.products (
  id            bigint generated by default as identity primary key,
  roaster_name  text        not null,
  region        text        not null,
  product_name  text        not null,
  origin        text        not null,
  process       text        not null,
  roast_level   text        not null check (roast_level in ('Light', 'Medium', 'Dark')),
  altitude      text,
  flavour_notes text[]      not null default '{}',
  description   text        not null default '',
  price         integer     not null,
  formats       jsonb       not null default '[]',
  seller_type   text        not null check (seller_type in ('Roastery', 'Café Roaster')),
  batch_info    jsonb,
  created_at    timestamptz not null default now()
);


-- 2. Row Level Security ───────────────────────────────────────────────────────

alter table public.products enable row level security;

-- Public read (anon key is safe — this is a public marketplace)
create policy "Products are publicly readable"
  on public.products
  for select
  to anon
  using (true);


-- 3. Seed data ────────────────────────────────────────────────────────────────

insert into public.products
  (roaster_name, region, product_name, origin, process, roast_level, altitude, flavour_notes, description, price, formats, seller_type, batch_info)
values

  (
    'Fuglen Tokyo', 'Tokyo', 'Ethiopia Yirgacheffe',
    'Ethiopia', 'Natural', 'Light', '1,800–2,200m',
    ARRAY['Blueberry', 'Jasmine', 'Bright citrus'],
    'A natural-processed Yirgacheffe from the Gedeo zone, brought to life through Fuglen''s precise light roast. Expect a delicate, tea-like body with an intense berry sweetness and a sparkling citrus finish.',
    1800,
    '[{"name":"Whole Bean","grams":200,"price":1800},{"name":"Drip Bag","grams":120,"price":2200}]'::jsonb,
    'Roastery',
    null
  ),

  (
    'Bear Pond Espresso', 'Tokyo', 'Colombia El Paraíso',
    'Colombia', 'Washed', 'Medium', '1,750m',
    ARRAY['Brown sugar', 'Stone fruit', 'Chocolate'],
    'From Diego Bermúdez''s El Paraíso farm in Huila, this washed lot is a study in balance — sweet and clean, with a lingering milk-chocolate finish. Bear Pond roasts it weekly in small batches.',
    2200,
    '[{"name":"Whole Bean","grams":200,"price":2200}]'::jsonb,
    'Café Roaster',
    '{"nextRoastDate":"2026-05-24","bagsRemaining":12}'::jsonb
  ),

  (
    '% Arabica', 'Kyoto', 'Guatemala Huehuetenango',
    'Guatemala', 'Washed', 'Light', '1,500–1,900m',
    ARRAY['Floral', 'Peach', 'Honey'],
    'Grown in one of Guatemala''s highest and most isolated regions, this lot reflects % Arabica''s meticulous green selection. The high altitude and volcanic soil produce a naturally honey-sweet cup.',
    2400,
    '[{"name":"Whole Bean","grams":200,"price":2400},{"name":"Drip Bag","grams":120,"price":2800}]'::jsonb,
    'Roastery',
    null
  ),

  (
    'Kurasu', 'Kyoto', 'Ethiopia Guji',
    'Ethiopia', 'Natural', 'Light', '2,000–2,200m',
    ARRAY['Strawberry', 'Peach', 'Cream'],
    'A wildly fruity natural from the Guji zone in southern Ethiopia. Kurasu sources direct from smallholder producers and roasts in micro-batches to preserve every layer of the vivid berry character.',
    1950,
    '[{"name":"Whole Bean","grams":200,"price":1950},{"name":"Drip Bag","grams":120,"price":2400}]'::jsonb,
    'Café Roaster',
    '{"nextRoastDate":"2026-05-22","bagsRemaining":8}'::jsonb
  ),

  (
    'Mameya Kakeru', 'Tokyo', 'Kenya Gicherori',
    'Kenya', 'Washed', 'Medium', '1,700–1,800m',
    ARRAY['Blackcurrant', 'Grapefruit', 'Walnut'],
    'The Gicherori washing station in Kirinyaga county processes SL28 and SL34 cherries from surrounding smallholders. Bright, winey, and intensely structured — a benchmark for Kenyan filter coffee.',
    3200,
    '[{"name":"Whole Bean","grams":200,"price":3200}]'::jsonb,
    'Roastery',
    null
  ),

  (
    'Nishiya Coffee', 'Osaka', 'Brazil Cerrado Mineiro',
    'Brazil', 'Natural', 'Dark', '900–1,100m',
    ARRAY['Dark chocolate', 'Caramel', 'Hazelnut'],
    'A bold, comforting cup from the Cerrado plateau in Minas Gerais. Nishiya''s extended development roast brings out a deep, roasty sweetness ideal for espresso and milk-based drinks.',
    1600,
    '[{"name":"Whole Bean","grams":200,"price":1600},{"name":"Drip Bag","grams":120,"price":1900}]'::jsonb,
    'Café Roaster',
    '{"nextRoastDate":"2026-05-26","bagsRemaining":20}'::jsonb
  );
